/**
 * PatientLookup.tsx  —  Live "Patient Registry" table
 * ─────────────────────────────────────────────────────
 * Subscribes to Firestore via `useLiveSessions` (onSnapshot).
 * The table refreshes automatically when a new session document
 * is written by the Python AI service — no page reload required.
 *
 * Badge colours:
 *   HIGH RISK   → red   (#f87171 / rgba(239,68,68,0.15))
 *   NORMAL      → cyan  (#13ecb6 / rgba(19,236,182,0.15))
 *
 * CSV download uses the signed URL stored in the Firestore document
 * (generated by the Python microservice via firebase-admin).
 */
import { History, Download, FileAudio, UserCircle, Calendar, Wifi } from "lucide-react";
import { useLiveSessions, getRiskBadge } from "@/hooks/use-sessions";

// ─── Live dot indicator (pulses when live) ───────────────────────────────────
function LiveDot() {
  return (
    <span className="relative flex h-2.5 w-2.5">
      <span
        className="animate-ping absolute inline-flex h-full w-full rounded-full opacity-70"
        style={{ background: "#13ecb6" }}
      />
      <span
        className="relative inline-flex rounded-full h-2.5 w-2.5"
        style={{ background: "#13ecb6" }}
      />
    </span>
  );
}

// ─── Component ───────────────────────────────────────────────────────────────
export function PatientLookup({ userId }: { userId?: string }) {
  const { sessions, isLoading, error } = useLiveSessions(userId);

  return (
    <div
      className="rounded-2xl p-6 flex flex-col gap-5"
      style={{ background: "#162c26", border: "1px solid #32675a" }}
    >
      {/* Header */}
      <div className="flex items-center justify-between pb-4 border-b border-[#32675a]/50">
        <h3 className="text-xl font-bold flex items-center gap-2">
          <History className="w-5 h-5 text-[#13ecb6]" />
          Patient Registry
        </h3>
        <div className="flex items-center gap-2 text-xs font-medium text-[#13ecb6]">
          <Wifi className="w-3.5 h-3.5" />
          <LiveDot />
          <span>Live</span>
        </div>
      </div>

      {/* Table / states */}
      <div className="flex-1 rounded-xl p-1 bg-black/20 border border-white/5 overflow-hidden">
        {isLoading ? (
          <div className="flex flex-col items-center justify-center p-12 gap-3 text-[#92c9bb]">
            <div
              className="w-8 h-8 rounded-full border-2 animate-spin"
              style={{
                borderColor: "rgba(19,236,182,0.3)",
                borderTopColor: "#13ecb6",
              }}
            />
            <p className="text-sm">Connecting to Firestore…</p>
          </div>
        ) : error ? (
          <div className="flex flex-col items-center justify-center p-12 text-red-400 gap-3">
            <UserCircle className="w-10 h-10 opacity-20" />
            <p className="text-sm">Failed to load history.</p>
            <p className="text-xs opacity-60">{error.message}</p>
          </div>
        ) : sessions.length === 0 ? (
          <div className="flex flex-col items-center justify-center p-12 text-[#92c9bb] gap-3">
            <UserCircle className="w-10 h-10 opacity-20" />
            <p className="text-sm">No tests recorded yet.</p>
            <p className="text-xs opacity-50">
              Start a diagnostic session to see results here.
            </p>
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-left text-sm text-white">
              <thead className="bg-[#10221d] text-[#92c9bb] uppercase text-[10px] font-black tracking-wider border-b border-[#32675a]">
                <tr>
                  <th className="px-4 py-4">Patient Name</th>
                  <th className="px-4 py-4">Date &amp; Time</th>
                  <th className="px-4 py-4">MCI Probability</th>
                  <th className="px-4 py-4">AI Verdict</th>
                  <th className="px-4 py-4 text-right">Data Export</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-[#32675a]/50">
                {sessions.map((session) => {
                  const { label, isHighRisk } = getRiskBadge(session);
                  return (
                    <tr
                      key={session.id}
                      className="hover:bg-white/5 transition-colors"
                    >
                      {/* Patient name */}
                      <td className="px-4 py-4 font-bold">
                        <div className="flex items-center gap-3">
                          <div
                            className="w-8 h-8 rounded-full flex items-center justify-center font-bold border text-xs"
                            style={{
                              background: "rgba(19,236,182,0.1)",
                              color: "#13ecb6",
                              borderColor: "rgba(19,236,182,0.2)",
                            }}
                          >
                            {session.patient_name?.charAt(0).toUpperCase() ?? "P"}
                          </div>
                          {session.patient_name}
                        </div>
                      </td>

                      {/* Date */}
                      <td className="px-4 py-4 text-[#92c9bb]">
                        <div className="flex items-center gap-1.5">
                          <Calendar className="w-3.5 h-3.5 shrink-0" />
                          {session.created_at?.toDate
                            ? session.created_at.toDate().toLocaleString()
                            : session.created_at
                              ? new Date(session.created_at).toLocaleString()
                              : "—"}
                        </div>
                      </td>

                      {/* MCI Probability */}
                      <td className="px-4 py-4">
                        <span
                          className="font-bold"
                          style={{
                            color: isHighRisk ? "#f87171" : "#13ecb6",
                          }}
                        >
                          {session.mci_probability.toFixed(1)}%
                        </span>
                      </td>

                      {/* Verdict badge */}
                      <td className="px-4 py-4">
                        <span
                          className="px-2.5 py-1 rounded-md font-bold text-xs inline-flex items-center gap-1.5"
                          style={{
                            background: isHighRisk
                              ? "rgba(239,68,68,0.15)"
                              : "rgba(19,236,182,0.15)",
                            color: isHighRisk ? "#f87171" : "#13ecb6",
                          }}
                        >
                          <span
                            className="w-1.5 h-1.5 rounded-full"
                            style={{
                              background: isHighRisk ? "#f87171" : "#13ecb6",
                            }}
                          />
                          {label}
                        </span>
                      </td>

                      {/* Data export */}
                      <td className="px-4 py-4 text-right">
                        {session.csv_url || session.heatmap_url || session.report_url ? (
                          <div className="flex items-center justify-end gap-2">
                            {session.heatmap_url && (
                              <a
                                href={session.heatmap_url}
                                target="_blank"
                                rel="noreferrer"
                                className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-bold transition-all hover:-translate-y-0.5"
                                style={{
                                  background: "rgba(19,236,182,0.1)",
                                  color: "#13ecb6",
                                  border: "1px solid rgba(19,236,182,0.3)",
                                }}
                                title="Download spectral heatmap PNG"
                              >
                                <FileAudio className="w-3.5 h-3.5" />
                                Spectrogram
                              </a>
                            )}
                            {session.report_url && (
                              <a
                                href={session.report_url}
                                download
                                className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-bold transition-all hover:-translate-y-0.5"
                                style={{
                                  background: "rgba(19,236,182,0.1)",
                                  color: "#13ecb6",
                                  border: "1px solid rgba(19,236,182,0.3)",
                                }}
                                title="Download Full Report"
                              >
                                <Download className="w-3.5 h-3.5" />
                                Full Report
                              </a>
                            )}
                            {session.csv_url && (
                              <a
                                href={session.csv_url}
                                download
                                className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-bold transition-all hover:-translate-y-0.5"
                                style={{
                                  background: "#13ecb6",
                                  color: "#0b1714",
                                  boxShadow: "0 4px 12px rgba(19,236,182,0.15)",
                                }}
                                title="Download raw EEG CSV (Firebase Storage signed URL)"
                              >
                                <Download className="w-3.5 h-3.5" />
                                CSV Data
                              </a>
                            )}
                          </div>
                        ) : (
                          <span className="text-xs text-[#92c9bb]/50 italic">
                            No files
                          </span>
                        )}
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        )}
      </div>

      {/* Footer */}
      {sessions.length > 0 && (
        <p className="text-xs text-[#92c9bb]/50 text-right">
          {sessions.length} session{sessions.length !== 1 ? "s" : ""} — updates
          in real-time via Firestore
        </p>
      )}
    </div>
  );
}
